import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DatastoreService {

  constructor() { }
  getAllRoad(){
    return [
      { name: 'Quốc lộ 1', from: 'Cầu Đồng Nai', to: 'Nút giao cầu vượt Trạm 2', district: 'Quận TĐ, 9' },
      { name: 'Quốc lộ 1', from: 'Nguyễn Văn Linh', to: 'Ranh Long An', district: 'Bình Chánh' },
      { name: 'Quốc lộ 1K', from: 'Cầu vượt Linh Xuân', to: 'Ranh tỉnh Bình Dương', district: 'Quận TĐ' },
      { name: 'Quốc lộ 13', from: 'Cầu Bình Triệu', to: 'Ranh tỉnh Bình Dương', district: 'Quận TĐ' },
      { name: 'Tô Ký', from: 'Cầu vượt Quang Trung', to: 'Lý Thường Kiệt', district: '12, Hóc Môn' },
      { name: 'Tỉnh lộ 10', from: 'An Dương Vương', to: 'Ranh Long An', district: 'Bình Tân, Bình Chánh' },
      { name: 'Quốc lộ 50', from: 'Nguyễn Văn Linh', to: 'Ranh Long An', district: 'Bình Chánh' },
      { name: 'Đường Rừng Sác', from: 'Phà Bình Khánh', to: 'Duyên Hải', district: 'Cần Giờ' },
      { name: 'Tuyến nhánh 1', from: 'Chợ Đệm', to: 'Bình Thuận', district: 'Bình Chánh' },
      { name: 'Tuyến nhánh 2', from: 'Chợ Đệm', to: 'Tân Tạo', district: 'Bình Chánh' },
      { name: 'Quốc lộ 1', from: 'Nút giao cầu vượt Trạm 2', to: 'Nguyễn Văn Linh', district: 'Bình Tân, Bình Chánh, 12' },
      { name: 'Nguyễn Văn Linh', from: 'Quốc lộ 1', to: 'Nút giao Khu A', district: 'Bình Chánh - Q7' },
      { name: 'Vành đai Đông', from: 'Nút Khu A', to: 'Liên tỉnh lộ 25B', district: 'Quận 2' },
      { name: 'Trường Chinh', from: 'Vòng xoay An Sương', to: 'Lý Thường Kiệt', district: 'Tân Bình, 12' },
      { name: 'Đường CMT8', from: 'Ngã tư Bảy Hiền', to: 'VX Phù Đổng Thiên Vương', district: 'Quận 10, 3, Tân Bình, 1' },
      { name: 'Nguyễn Thị Nghĩa', from: 'VX Phù Đổng Thiên Vương', to: 'Đường Phạm Ngũ Lão', district: 'Quận 1' },
      { name: 'Nguyễn Thái Học', from: 'Đường Trần Hưng Đạo', to: 'Cầu Ông Lãnh', district: 'Quận 1' },
      { name: 'Hòang Diệu', from: 'Đường Nguyễn Tất Thành', to: 'Đường Khánh Hội', district: 'Quận 4' },
      { name: 'Khánh Hội', from: 'Đường Hòang Diệu', to: 'Cầu Kênh Tẻ', district: 'Quận 4' },
      { name: 'Đường Võ Văn Kiệt', from: 'Quốc lộ 1', to: 'Đường hầm sông Sài Gòn', district: 'Quận 1,5,6' },
      { name: 'Đại lộ Đông Tây', from: 'Đường hầm sông Sài Gòn', to: 'Nút giao Cát Lái ', district: 'Quận 2' },
      { name: 'Xa lộ Hà Nội', from: 'Nút giao cầu vượt Trạm 2', to: 'Cầu Sài Gòn', district: 'Quận 2' },
      { name: 'Hoàng Văn Thụ', from: 'Đường CMT8', to: 'Đường Phan Đình Phùng', district: 'Quận Phú Nhuận, Tân Bình' },
      { name: 'Cộng Hòa', from: 'Trường Chinh', to: 'Hoàng Văn Thụ', district: 'Quận Tân Bình' },
      { name: 'Phan Huy Ích', from: 'Trường Chinh', to: 'Quang Trung', district: 'Gò Vấp, Tân Bình' },
      { name: 'Võ Thị Sáu', from: 'Đinh Tiên Hoàng', to: 'VX Dân Chủ', district: 'Quận 1, 3' },
      { name: 'Đường 3 tháng 2', from: 'Cách Mạng Tháng 8', to: 'Hồng Bàng', district: 'Quận 10' },
      { name: 'Điện Biên Phủ', from: 'Lý Thái Tổ', to: 'Cầu Điện Biên Phủ', district: 'Quận 1, 3, 10' },
      { name: 'Điện Biên Phủ', from: 'Cầu Điện Biên Phủ', to: 'Cầu Sài Gòn', district: 'Quận Bình Thạnh' },
      { name: 'Nguyễn Hữu Cảnh', from: 'Cầu Sài Gòn', to: 'Tôn Đức Thắng', district: 'Quận Bình Thạnh' },
      { name: 'Xô Viết Nghệ Tĩnh', from: 'Đài Liệt Sĩ', to: 'Cầu Thị Nghè', district: 'Quận Bình Thạnh' },
      { name: 'Nguyễn Thị Minh Khai', from: 'Cầu Thị Nghè', to: 'Nguyễn Văn Cừ', district: 'Quận 1, 3' },
      { name: 'An Dương Vương', from: 'Tân Hòa Đông', to: 'Cầu Mỹ Thuận', district: 'Quận 6' },
      { name: 'Hồng Bàng', from: 'Ngô Quyền', to: 'Vòng xoay Phú Lâm', district: 'Quận 6' },
      { name: 'Kinh Dương Vương', from: 'Vòng xoay Phú Lâm', to: 'Vòng xoay An Lạc', district: 'Quận 6' },
      { name: 'Trần Hưng Đạo', from: 'QT. Quách Thị Trang', to: 'Châu Văn Liêm', district: 'Quận 1,5' },
      { name: 'Quốc lộ 50 ', from: 'Nguyễn Văn Linh', to: 'Cầu Nhị Thiên Đường', district: 'Bình Chánh -Q8' },
      { name: 'Trần Xuân Soạn', from: 'Cầu Rạch Ong', to: 'Huỳnh Tấn Phát', district: 'Quận 7' },
      { name: 'Tạ Quang Bửu', from: 'Nguyễn Thị Tần', to: 'hẻm 2385B', district: 'Quận 8' },
      { name: 'Hưng Phú', from: 'Cầu Chữ Y', to: 'Xóm Củi', district: 'Quận 8' },
      { name: 'Nguyễn Thị Thập', from: 'Cầu Him Lam', to: 'Huỳnh Tấn Phát', district: 'Quận 7' },
      { name: 'Phan Văn Trị', from: 'Thống Nhất', to: 'Nơ Trang Long', district: 'Gò Vấp, Bình Thạnh' },
      { name: 'Tôn Đức Thắng', from: 'Nguyễn Hữu Cảnh', to: 'Hàm Nghi', district: 'Quận 1' },
      { name: 'Nguyễn Tất Thành', from: 'Cầu Khánh Hội', to: 'Cầu Tân Thuận', district: 'Quận 4' },
      { name: 'Huỳnh Tấn Phát', from: 'Trần Xuân Soạn', to: 'Phà Bình Khánh', district: 'Quận 7' },
      { name: 'Lê Văn Lương', from: 'Trần Xuân Soạn', to: 'Cầu Rạch Đĩa 1', district: 'Quận 7' },
      { name: 'Quang Trung', from: 'Điểm cuối', to: 'Lý Thường Kiệt', district: 'Hóc Môn' },
      { name: 'Hà Huy Giáp', from: 'Cầu Phú Long', to: 'Cầu An Lộc', district: '12' },
      { name: 'Nguyễn Kiệm ', from: 'Hoàng Văn Thụ', to: 'Ngã 6 Gò Vấp', district: 'Phú Nhuận, Gò Vấp' },
      { name: 'Nguyễn Văn Trỗi', from: 'Hoàng Văn Thụ', to: 'Cầu Công Lý', district: 'Quận Phú Nhuận' },
      { name: 'Nam Kỳ Khởi Nghĩa', from: 'Cầu Công Lý', to: 'Võ Văn Kiệt', district: 'Quận 3' },
      { name: 'Lý Thái Tổ', from: 'Nguyễn Thị Minh Khai', to: '3 tháng 2', district: 'Quận 3, 10' },
      { name: 'Nguyễn Tri Phương', from: 'Trần Hưng Đạo', to: '3 tháng 2', district: 'Quận 5, 10' },
      { name: 'Thành Thái', from: '3 tháng 2', to: 'Bắc Hải', district: 'Quận 10' },
      { name: 'Chánh Hưng', from: 'Nguyễn Văn Linh', to: 'Cầu Chánh Hưng', district: 'Bình Chánh -Q8' },
      { name: 'Lý Thường Kiệt', from: 'Hồng Bàng', to: 'CMT8', district: 'Quận 10,11' },
      { name: 'Lạc Long Quân', from: 'Tân Hóa', to: 'Lý Thường Kiệt', district: 'Quận 11, Tân Bình' },
      { name: 'Đặng Thúc Vịnh', from: 'Quang Trung', to: 'Cầu Rạch Tra', district: 'Hóc Môn' },
      { name: 'Hà Duy Phiên', from: 'Cầu Rạch Tra', to: 'Tỉnh lộ 8', district: 'Củ Chi' },
      { name: 'Tỉnh lộ 8', from: 'Cầu Thầy Cai', to: 'Cầu Phú Cường', district: 'Củ Chi' },
      { name: 'Tỉnh lộ 7', from: 'Cầu Tân Thái', to: 'Tỉnh lộ 15', district: 'Củ Chi' },
      { name: 'Liên Tỉnh Lộ 25B', from: 'Đại lộ Đông Tây', to: 'Phà Cát Lái', district: 'Quận 2' },
      { name: 'Phạm Thế Hiển', from: 'Cầu Rạch Ông', to: 'Trịnh Quang Nghị', district: 'Quận 8' },
      { name: 'Nguyễn Văn Nghi', from: 'cầu Hang Ngoài', to: 'Ngã 6 Gò Vấp', district: 'Gò Vấp' },
      { name: 'Lê Quang Định', from: 'Bạch Đằng', to: 'cầu Hang Ngoài', district: 'Gò Vấp, Bình Thạnh' },
      { name: 'Bùi Công Trừng', from: 'Hà Huy Giáp', to: 'Đặng Thúc Vịnh', district: '12, Hóc Môn' },
      { name: 'Lê Văn Khương', from: 'Quốc lộ 1A', to: 'Đặng Thúc Vịnh', district: '12, Hóc Môn' },
      { name: 'Nguyễn Anh Thủ', from: 'Lê Văn Khương', to: 'Phan Văn Hớn', district: '12, Hóc Môn' },
      { name: 'Dương Công Khi', from: 'Ranh Bình Chánh', to: 'Quốc lộ 22', district: 'Hóc Môn' },
      { name: 'Nguyễn Văn Bứa', from: 'Ranh Long An', to: 'Quốc lộ 22', district: 'Hóc Môn' },
      { name: 'Hương lộ 2', from: 'Quốc lộ 22', to: 'Ranh Tây Ninh', district: 'Củ Chi' },
      { name: 'Nguyễn Xí', from: 'Đài Liệt Sĩ', to: 'Nơ Trang Long', district: 'Quận Bình Thạnh' },
      { name: 'Đinh Bộ Lĩnh', from: 'Cầu Bình Triệu', to: 'Điện Biên Phủ', district: 'Quận Bình Thạnh' },
      { name: 'Bạch Đằng', from: 'Nguyễn Kiệm', to: 'Đường A75 - Trường Sơn', district: 'Quận Tân Bình' },
      { name: 'Phan Đăng Lưu', from: 'Bạch Đằng', to: 'Hoàng Văn Thụ', district: 'Quận Bình Thạnh' },
      { name: 'Nơ Trang Long', from: 'Phan Đăng Lưu', to: 'Bình Lợi', district: 'Quận Bình Thạnh' },
      { name: 'Quốc lộ 13', from: 'Đài Liệt Sĩ', to: 'Cầu Bình Triệu', district: 'Quận Bình Thạnh' },
      { name: 'Nguyễn Văn Linh', from: 'Nút giao Khu A', to: 'Huỳnh Tấn Phát', district: 'Quận 7' },
      { name: 'Song hành Quốc lộ 22', from: 'Kênh Tham Lương', to: 'Hương lộ 65', district: '12, Hóc Môn' },
      { name: 'Kinh Dương Vương', from: 'Vòng xoay Phú Lâm', to: 'Vòng xoay An Lạc', district: 'Quận Bình Tân' }
    ];
  }
}
