version: '3.5'

services:
  backend:
    image: ttgt-backend
    ports: 
      - 3000:3000
    build:
      context: ../backend
      dockerfile: Dockerfile

  client:
    image: ttgt-client
    ports: 
      - 9000:9000
    build:
      context: ../client
      dockerfile: Dockerfile